import { NewsAlert } from '../types/watch';

/**
 * Normalizes an article title for accurate semantic deduplication.
 * Strips out media prefixes (e.g. "Alter Échos :", "RTBF Info :"),
 * time tags (e.g. "[11h36]", "[14:20]"), quotes, and non-alphanumeric noise.
 */
export function normalizeTitleForDeduplication(rawTitle: string): string {
  if (!rawTitle) return '';
  let t = rawTitle.toLowerCase().trim();

  // Strip media prefixes like "Alter Échos :", "RTBF Info :", "L'Avenir :", etc.
  t = t.replace(
    /^(?:alter\s*échos|alter\s*echos|rtbf(?:\s*info)?|l['’]avenir|la\s*libre(?:\.be)?|le\s*soir|l['’]écho|l['’]echo|dhnet|sudinfo|solidaire|basta!?|médor|medor|belga(?:\s*news\s*agency)?|cumuleo|transparencia|defakator|hygiène\s*mentale|mr\s*phi|clément\s*viktorovitch|blast|mediapart)\s*[:–—-]\s*/i,
    ''
  );

  // Strip dynamic time brackets like [11h36], [14h20], (11h36), [11:36]
  t = t.replace(/\[\s*\d{1,2}\s*[h:]\s*\d{2}\s*\]/gi, '');
  t = t.replace(/\(\s*\d{1,2}\s*[h:]\s*\d{2}\s*\)/gi, '');

  // Strip quotes and accents-insensitive clean
  t = t.replace(/[«»"“”'’`]/g, ' ');

  // Remove punctuation
  t = t.replace(/[.,:;!?()[\]{}<>/\\|@#$%^&*~+=_-]/g, ' ');

  // Normalize spaces
  t = t.replace(/\s+/g, ' ').trim();

  return t;
}

/**
 * Canonicalizes an article URL to detect duplicate links across feeds.
 * Strips UTM parameters, tracking IDs, trailing slashes and hash anchors.
 */
export function canonicalizeUrl(rawUrl?: string): string {
  if (!rawUrl) return '';
  const trimmed = rawUrl.trim();
  if (!trimmed) return '';

  try {
    const parsed = new URL(trimmed);
    // Ignore generic Google search URLs as identifiers
    if (parsed.hostname.includes('google.') && parsed.pathname.includes('/search')) {
      return '';
    }

    // Strip common tracking and social referral params
    const trackingParams = [
      'utm_source',
      'utm_medium',
      'utm_campaign',
      'utm_term',
      'utm_content',
      'fbclid',
      'gclid',
      'ref',
      'source',
      'at_medium',
      'at_campaign',
    ];
    for (const param of trackingParams) {
      parsed.searchParams.delete(param);
    }

    // Normalize protocol
    parsed.protocol = 'https:';

    // Strip hash
    parsed.hash = '';

    // Strip trailing slash
    let out = parsed.toString();
    if (out.endsWith('/')) {
      out = out.slice(0, -1);
    }
    return out.toLowerCase();
  } catch {
    return trimmed.toLowerCase().replace(/\/+$/, '');
  }
}

/**
 * Detects if an alert is a synthetic template generated by earlier buggy scans
 * (e.g. repeated "Alter Échos : Mobilisation et défense des droits [11h14]...").
 */
export function isSyntheticAlert(alert: Partial<NewsAlert>): boolean {
  if (!alert) return false;
  const id = (alert.id || '').toLowerCase();
  const title = (alert.title || '').toLowerCase();

  // Synthetic IDs
  if (id.startsWith('alert-fresh-')) return true;

  // Synthetic recurring title patterns
  if (title.includes('mobilisation et défense des droits') && title.includes('nouvelles revendications citoyennes')) {
    return true;
  }
  if (title.includes('débats budgétaires et dialogue social') && title.includes('les réactions patronales')) {
    return true;
  }
  if (/(?:alter\s*échos|l['’]écho)\s*:.*\[\s*\d{1,2}\s*h\s*\d{2}\s*\]/i.test(alert.title || '')) {
    return true;
  }

  return false;
}

/**
 * Calculates word overlap coefficient (Dice coefficient on significant words).
 */
function wordSimilarity(textA: string, textB: string): number {
  if (!textA || !textB) return 0;
  if (textA === textB) return 1;

  const wordsA = new Set(
    textA
      .split(' ')
      .filter((w) => w.length >= 4)
  );
  const wordsB = new Set(
    textB
      .split(' ')
      .filter((w) => w.length >= 4)
  );

  if (wordsA.size === 0 || wordsB.size === 0) return 0;

  let intersection = 0;
  for (const w of wordsA) {
    if (wordsB.has(w)) intersection++;
  }

  return (2 * intersection) / (wordsA.size + wordsB.size);
}

/**
 * Checks if two alerts are duplicate articles.
 */
export function areAlertsDuplicate(
  alertA: Partial<NewsAlert>,
  alertB: Partial<NewsAlert>
): boolean {
  if (!alertA || !alertB) return false;

  // 1. Check exact or canonical URL
  const canonA = canonicalizeUrl(alertA.sourceUrl);
  const canonB = canonicalizeUrl(alertB.sourceUrl);
  if (canonA && canonB && canonA === canonB) {
    return true;
  }

  // 2. Check normalized titles
  const normA = normalizeTitleForDeduplication(alertA.title || '');
  const normB = normalizeTitleForDeduplication(alertB.title || '');

  if (normA && normB) {
    if (normA === normB) return true;

    // Substring containment if titles are sufficiently long
    if (normA.length >= 30 && normB.length >= 30) {
      if (normA.includes(normB) || normB.includes(normA)) return true;
    }

    // High word similarity check (e.g. > 80% shared meaningful words)
    const sim = wordSimilarity(normA, normB);
    if (sim >= 0.8) return true;

    // If both belong to the same source and have high similarity >= 0.68
    const srcA = (alertA.source || '').toLowerCase().trim();
    const srcB = (alertB.source || '').toLowerCase().trim();
    if (srcA && srcB && (srcA.includes(srcB) || srcB.includes(srcA))) {
      if (sim >= 0.68) return true;
    }
  }

  return false;
}

/**
 * Checks if a candidate alert already exists in an existing collection of alerts.
 */
export function isDuplicateInCollection(
  candidate: Partial<NewsAlert>,
  collection: NewsAlert[]
): boolean {
  if (isSyntheticAlert(candidate)) return true;
  return collection.some((existing) => areAlertsDuplicate(candidate, existing));
}

/**
 * Purges duplicate articles from an array, removes synthetic artifacts,
 * and preserves only the highest-quality version of each unique article.
 */
export function purgeDuplicateAlerts(alertsList: NewsAlert[]): NewsAlert[] {
  const result: NewsAlert[] = [];

  for (const item of alertsList) {
    // 1. Immediately drop synthetic dummy alerts
    if (isSyntheticAlert(item)) {
      continue;
    }

    // 2. Check if already present in accumulated result
    const isDup = result.some((existing) => areAlertsDuplicate(item, existing));
    if (!isDup) {
      result.push(item);
    }
  }

  return result;
}
